/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package preliminares;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author abell
 */
public class Pizarra extends javax.swing.JFrame {

    /**
     * Creates new form Pizarra2
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    private Graphics pintor;
    
    public static void main(String args[]) {
        new Pizarra();
    }
    
    public Pizarra() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setSize(600,400);
        this.pintor=null;
        this.dibujador();
    }
    private void dibujador ()
    {
        this.pintor=this.jPanel1.getGraphics();
        
        this.pintor.drawString("Bienvenido, qué pintaremos hoy", 20, 20);
        
        this.pintor.setColor(Color.green);
        this.pintor.drawLine(30, 80, 230, 30);
        
        this.pintor.setColor(Color.red);
        this.pintor.drawLine(30, 80, 230, 30);
        
        this.pintor.drawString("Felipe Abella", 10, 10);
        
        this.pintor.setColor(Color.orange);
        this.pintor.drawRect(30, 90, 200, 40);
        
        this.pintor.setColor(Color.magenta);
        this.pintor.drawOval(30, 140, 80, 80);
        this.pintor.setColor(Color.blue);
        this.pintor.fillOval(30, 140, 80, 80);
        
        this.pintor.setColor(Color.black);
        this.pintor.drawOval(40, 180, 1, 1);
    }
}