/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Figura1;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author abell
 */
public class Pizarra extends javax.swing.JFrame {

    /**
     * Creates new form Pizarra
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setToolTipText("");
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel1.setText("DibujaPuntos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setToolTipText("");
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel2.setText("DibujaCírculos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setToolTipText("");
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel3.setText("Clear Screen");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(199, 199, 199))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setToolTipText("");
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel4.setText("DibujaEsfera");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setToolTipText("");
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel5.setText("DibujaCilindro");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        this.crearPunto();
        this.dibujarPunto();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        this.crearCirculo();
        this.dibujarCirculo();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.jPanel1.printAll(this.pintor);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        this.crearEsfera();
        this.dibujarEsfera();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        this.crearCilindro();
        this.dibujarCilindro();
    }//GEN-LAST:event_jPanel7MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

    private Punto puntico;
    private Circulo circulito;
    private Esfera esferita;
    private Cilindro cilindrito;
    private Graphics pintor;
    
    public static void main(String args[]) {
     new Pizarra();   
    }
    
    public Pizarra() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.pintor=this.jPanel1.getGraphics();
    }
    
    private void crearPunto()
    {
        int x,y;
        x=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada x del punto: "));
        y=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada y del punto: "));
        
        this.puntico=new Punto(x,y);
    }
    
    private void dibujarPunto()
    {
        int r,g,b;
        r=(int)(255*Math.random());
        g=(int)(255*Math.random());
        b=(int)(255*Math.random());
        Color colorcito=new Color(r,g,b);
        this.pintor.setColor(colorcito);
        this.pintor.drawOval(this.puntico.getX(), this.puntico.getY(), 1, 1);
    }
    
    private void crearCirculo()
    {
        int x,y,radio;
        x=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada x del círculo: "));
        y=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada y del círculo: "));
        radio=Integer.parseInt(JOptionPane.showInputDialog("Digite el radio del círculo: "));
        this.circulito=new Circulo(x,y,radio);
    }
    
    private void dibujarCirculo()
    {
        int r,g,b,respuesta;
        String propiedades="";
        r=(int)(255*Math.random());
        g=(int)(255*Math.random());
        b=(int)(255*Math.random());
        Color colorcito=new Color(r,g,b);
        this.pintor.setColor(colorcito);
        this.pintor.drawOval(this.circulito.getX()-this.circulito.getRadio(), this.circulito.getY()-this.circulito.getRadio(), 2*this.circulito.getRadio(),2*this.circulito.getRadio());
        this.pintor.drawOval(this.circulito.getX(), this.circulito.getY(), 1, 1);
        
        respuesta=Integer.parseInt(JOptionPane.showInputDialog("¿Desea ver las propiedades del círculo? (1=Sí, 2=No)"));
        if(respuesta==1)
        {
            propiedades+="Centro (+"+this.circulito.getX()+", "+this.circulito.getY()+")\n"
                    + "Radio: "+this.circulito.getRadio()+"\n"
                    + "Perímetro: "+this.circulito.getPerimetro()+"\n"
                    + "Área: "+this.circulito.getArea();
            JOptionPane.showMessageDialog(null, propiedades);
        }
    }
    
    private void crearEsfera()
    {
        int x,y,radio;
        
        x=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada x de la esfera: "));
        y=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada y de la esfera: "));
        radio=Integer.parseInt(JOptionPane.showInputDialog("Digite el radio de la esfera: "));
        this.esferita=new Esfera(x,y,radio);
    }
    
    private void dibujarEsfera()
    {
        int r,g,b,respuesta;
        String propiedades="";
        
        r=(int)(255*Math.random());
        g=(int)(255*Math.random());
        b=(int)(255*Math.random());
        
        Color colorcito=new Color(r,g,b);
        
        this.pintor.setColor(colorcito);
        this.pintor.drawOval(this.esferita.getX()-this.esferita.getRadio(), this.esferita.getY()-this.esferita.getRadio(), 2*this.esferita.getRadio(),2*this.esferita.getRadio());
        this.pintor.fillOval(this.esferita.getX()-this.esferita.getRadio(), this.esferita.getY()-this.esferita.getRadio()+5*this.esferita.getRadio()/6,2*this.esferita.getRadio(),this.esferita.getRadio()/3);
        this.pintor.setColor(colorcito);
        this.pintor.drawOval(this.esferita.getX(),this.esferita.getY(), 1, 1);
        respuesta=Integer.parseInt(JOptionPane.showInputDialog("¿Desea ver las propiedades del círculo? (1=Sí, 2=No)"));
        if(respuesta==1)
        {
            propiedades+="Centro (+"+this.esferita.getX()+", "+this.esferita.getY()+")\n"
                    + "Radio: "+this.esferita.getRadio()+"\n"
                    + "Volumen: "+this.esferita.getVolumen()+"\n"
                    + "Área: "+this.esferita.getArea();
            JOptionPane.showMessageDialog(null, propiedades);
        }
    }
    
    private void crearCilindro()
    {
        int x,y,radio,altura;
        
        x=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada x de la base del cilindro: "));
        y=Integer.parseInt(JOptionPane.showInputDialog("Digite la coordenada y de la base del cilindro: "));
        radio=Integer.parseInt(JOptionPane.showInputDialog("Digite el radio de la base del cilindro: "));
        altura=Integer.parseInt(JOptionPane.showInputDialog("Digite la altura del cilindro: "));
        this.cilindrito=new Cilindro(x,y,radio,altura);
    }
    
    private void dibujarCilindro()
    {
        int r,g,b,respuesta;
        String propiedades="";
        
        r=(int)(255*Math.random());
        g=(int)(255*Math.random());
        b=(int)(255*Math.random());
        
        Color colorcito=new Color(r,g,b);
        
        this.pintor.fillOval(this.cilindrito.getX()-this.cilindrito.getRadio(), this.cilindrito.getY()-this.cilindrito.getRadio()+5*this.cilindrito.getRadio()/6,2*this.cilindrito.getRadio(),this.cilindrito.getRadio()/3);
        this.pintor.fillOval(this.cilindrito.getX()-this.cilindrito.getRadio(), this.cilindrito.getY()-this.cilindrito.getRadio()+5*this.cilindrito.getRadio()/6-this.cilindrito.getAltura(),2*this.cilindrito.getRadio(),this.cilindrito.getRadio()/3);        
        
        this.pintor.drawLine(this.cilindrito.getX()-this.cilindrito.getRadio(), this.cilindrito.getY(), this.cilindrito.getX()-this.cilindrito.getRadio(), this.cilindrito.getY()-this.cilindrito.getRadio()-this.cilindrito.getAltura());
        this.pintor.drawLine(this.cilindrito.getX()+this.cilindrito.getRadio(), this.cilindrito.getY(), this.cilindrito.getX()+this.cilindrito.getRadio(), this.cilindrito.getY()-this.cilindrito.getRadio()-this.cilindrito.getAltura());
        
        this.pintor.setColor(colorcito);
        this.pintor.drawOval(this.cilindrito.getX(),this.cilindrito.getY(), 1, 1);
        
        respuesta=Integer.parseInt(JOptionPane.showInputDialog("¿Desea ver las propiedades del círculo? (1=Sí, 2=No)"));
        if(respuesta==1)
        {
            propiedades+="Centro (+"+this.esferita.getX()+", "+this.esferita.getY()+")\n"
                    + "Radio: "+this.esferita.getRadio()+"\n"
                    + "Volumen: "+this.esferita.getVolumen()+"\n"
                    + "Área: "+this.esferita.getArea();
            JOptionPane.showMessageDialog(null, propiedades);
        }
    }
}